name: everyday_dart
version: 0.0.1
description: Dart for everyday.
environment:
  sdk: '>=0.8.10 <0.9.0'
dependencies:
  logging: 0.8.10+3
  polymer: 0.8.10+3
  postgresql: 0.2.10
  route: 0.4.5+1
  serialization: 0.8.10+3
  unittest: 0.8.10+3
