name: everyday_dart
version: 0.0.1
description: Dart for everyday.
environment:
  sdk: '>=0.8.9 <0.9.0'
dependencies:
  logging: any
  polymer: any
  postgresql: any
  route: any
  serialization: any
  unittest: any
