name: everyday_dart
version: 0.0.1
description: Dart for everyday.
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  logging: '>=0.9.0 < 0.10.0'
  polymer: '>=0.9.0 < 0.10.0'
  postgresql: '>=0.2.11 < 0.3.0'
  route: '0.4.5+1'
  serialization: '>=0.9.0 < 0.10.0'
  unittest: '>=0.9.0 < 0.10.0'
transformers:
- polymer:
    entry_points:
    - web/client/index.html